### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by c4augustus** [danijoo/resdiff#1]
> java -jar resdiff-1.0.jar strings.xml strings-mod.xml

Exception in thread "main" java.lang.NullPointerException
	at net.headlezz.resdiff.Resource$Companion.fromElement(Resource.kt:18)
	at net.headlezz.resdiff.ResDiffKt.getResourcesFromFile(ResDiff.kt:160)
	at net.headlezz.resdiff.ResDiffKt.main(ResDiff.kt:38)
	at net.headlezz.resdiff.ResdiffPackage.main(ResDiff.kt:1)

**Comment by dnlbauer** [comment]
I haven't worked on that project or used it for a very long time. If yoy want to fix this and do a PR, you are more than welcome to do so.
